# yamllint disable-file
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: {{ .Values.argocd_namespace }}
spec:
  project: default
  source:
    repoURL: {{ .Values.gitops_repo_url | quote }}
    targetRevision: {{ .Values.gitops_target_revision | quote }}
    path: {{ .Values.gitops_apps_path | quote }}
    directory:
      recurse: true
      include: application.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.argocd_namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
