name: Trivy

on:
  pull_request:
  push:

jobs:
  trivy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: config
          scan-ref: .
          severity: CRITICAL
          exit-code: "1"
